import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "es";

const translations = {
  en: {
    workerPortal: "Worker Portal",
    adminPanel: "Admin Panel",
    language: "Language",
    english: "English",
    spanish: "Spanish",
    logout: "Sign Out",
    login: "Sign In",
    username: "Username",
    password: "Password",
    enterUsername: "Enter your username",
    enterPassword: "Enter your password",
    loginTitle: "Worker Access",
    loginSubtitle: "Sign in to log your attendance and daily updates",
    contactManager: "Contact your site manager for credentials",
    signingIn: "Signing in...",

    yourLocation: "Your Location",
    refreshGps: "Refresh GPS",
    gettingLocation: "Getting location...",
    attendance: "Attendance",
    onSite: "On site",
    offSite: "Off site",
    clockIn: "Clock In",
    clockOut: "Clock Out",
    clockingIn: "Getting GPS & clocking in...",
    clockingOut: "Getting GPS & clocking out...",
    clockedInAt: "Clocked in at",
    registeredAt: "Registered at",
    updateMyLocation: "Update My Location",
    updatingLocation: "Updating...",
    noGpsOnEntry: "No GPS recorded at clock-in",
    viewMap: "Map",
    viewOnMap: "View on map",
    gpsUnavailable: "GPS is not available on this device",
    gpsPermissionDenied: "Location access denied. Enable GPS in your browser settings.",
    gpsSignalUnavailable: "GPS signal not available. Try outside or in another location.",
    gpsTimeout: "Location request timed out. Try again.",
    gpsError: "Could not get location. Try again.",
    gpsWillBeRecorded: "Your GPS location will be recorded when you clock in",

    teamChat: "Team Chat",
    messages: "messages",
    noMessages: "No messages yet. Start the conversation!",
    typeMessage: "Type a message...",
    send: "Send",

    dailyUpdate: "Post Daily Update",
    whatDidYouWork: "What did you work on today? Describe your progress...",
    addPhoto: "Add photo",
    changePhoto: "Change photo",
    remove: "Remove",
    post: "Post",
    posting: "Posting...",
    yourUpdates: "Your Updates",
    locationUpdated: "Location updated",
    locationUpdatedDesc: "Your GPS location has been updated.",
    clockedIn: "Clocked In",
    clockedInWithGps: "You have clocked in with your GPS location.",
    clockedInNoGps: "You have clocked in (GPS not available).",
    clockedOut: "Clocked Out",
    clockedOutWithGps: "You have clocked out with your GPS location.",
    clockedOutNoGps: "You have clocked out (GPS not available).",
    updatePosted: "Update Posted",
    updatePostedDesc: "Your daily update has been sent.",

    leaveRequests: "Leave Requests",
    submitLeaveRequest: "Submit Leave Request",
    annualLeave: "Annual Leave",
    sickNote: "Sick Note",
    requestType: "Request Type",
    startDate: "Start Date",
    endDate: "End Date",
    additionalNotes: "Additional Notes (optional)",
    sickNotePhoto: "Sick Note Photo",
    attachSickNote: "Attach Sick Note Photo",
    changeSickNote: "Change Photo",
    submitRequest: "Submit Request",
    submitting: "Submitting...",
    myRequests: "My Requests",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    from: "From",
    to: "To",
    adminNote: "Admin note",
    requestSubmitted: "Request Submitted",
    requestSubmittedDesc: "Your leave request has been submitted.",
    noRequestsYet: "No requests submitted yet.",

    workers: "Workers",
    totalWorkers: "Total Workers",
    onSiteNow: "On Site Now",
    completed: "Completed Shift",
    activeSites: "Active Sites",
    currentlyOnSite: "Currently on site",
    completedShift: "Completed shift",
    noAttendanceToday: "No attendance records for this date.",
    active: "Active",
    done: "Done",
    noGps: "No GPS",
    export: "Export Excel",
    exportFrom: "Export from",
    payroll: "Payroll",
    sites: "Sites",
    activity: "Activity",
    requests: "Requests",
    allRequests: "All Leave Requests",
    noRequestsAdmin: "No leave requests yet.",
    approve: "Approve",
    reject: "Reject",
    viewSickNote: "View sick note",
    pendingRequests: "Pending",
    approvedRequests: "Approved",
    rejectedRequests: "Rejected",
    approveRequest: "Approve Request",
    rejectRequest: "Reject Request",
    optionalNote: "Optional note for worker...",
    confirm: "Confirm",
    cancel: "Cancel",
    requestApproved: "Request Approved",
    requestRejected: "Request Rejected",

    addWorker: "Add Worker",
    addNewWorker: "Add New Worker",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g. John Smith",
    usernamePlaceholder: "e.g. john.smith",
    passwordPlaceholder: "Set a password",
    shareWithWorker: "Share with worker:",
    copy: "Copy",
    createWorker: "Create Worker",
    creating: "Creating...",
    copied: "Copied",
    credentialsCopied: "Credentials copied to clipboard",
    workerCreated: "Worker Created",
    workerCreatedDesc: "New worker added successfully.",
    deleteWorker: "Delete worker",
    confirmDeleteWorker: "Delete",
    workerDeleted: "Worker Deleted",
    contract: "Contract",
    history: "History",
    noAttendanceYet: "No attendance records yet.",
    workerManagement: "Worker Management",
    contractExpired: "Expired",
    contractExpiringSoon: "Expiring Soon",
    contractExpiresIn: "Contract expires in",
    contractExpiredDaysAgo: "Contract expired",
    daysLeft: "days left in contract",
    daysAgo: "days ago",
    contractType: "Contract Type",
    assignedSite: "Assigned Site",
    hourlyRate: "Hourly Rate (£)",
    contractStart: "Contract Start Date",
    contractEnd: "Contract End Date",
    totalSickDays: "Total Sick Days",
    usedSickDays: "Sick Days Used",
    totalHolidayDays: "Total Holiday Days",
    usedHolidayDays: "Holiday Days Used",
    saveContract: "Save Contract Data",
    saving: "Saving...",
    contractUpdated: "Contract Updated",
    sickDaysLeft: "Sick days remaining",
    holidayDaysLeft: "Holiday days remaining",
    fullTime: "Full-time",
    partTime: "Part-time",
    temporary: "Temporary",
    byProject: "By Project",
    apprentice: "Apprentice",
    noAssignedSite: "No site assigned",

    payrollCalculator: "Payroll Calculator",
    noHourlyRate: "No rate set",
    hoursToday: "h today",
    setHourlyRate: "Set an hourly rate on each worker to see calculations here.",
    enableAlerts: "Enable Alerts",
    alertsEnabled: "Alerts On",

    addSite: "Add Site",
    addSiteTitle: "Add Site",
    siteName: "Site Name",
    siteNamePlaceholder: "e.g. City Centre Building",
    siteAddress: "Address (optional)",
    siteAddressPlaceholder: "e.g. 123 Main Street",
    adding: "Adding...",
    noSitesYet: "No sites yet. Add the first one above.",
    noWorkersAssigned: "No workers assigned",
    assignedWorkers: "Workers",
    deleteSite: "Delete site",
    siteAdded: "Site Added",
    siteDeleted: "Site Deleted",

    activityTitle: "Worker Updates",
    noActivityYet: "No updates yet. Workers can post from their portal.",
    unknown: "Unknown",

    attendanceHistory: "Attendance History",
    viewDate: "View Date",
    today: "Today",
  },
  es: {
    workerPortal: "Portal del Trabajador",
    adminPanel: "Panel de Administración",
    language: "Idioma",
    english: "Inglés",
    spanish: "Español",
    logout: "Salir",
    login: "Entrar",
    username: "Usuario",
    password: "Contraseña",
    enterUsername: "Introduce tu usuario",
    enterPassword: "Introduce tu contraseña",
    loginTitle: "Acceso de Trabajador",
    loginSubtitle: "Inicia sesión para registrar tu asistencia y actualizaciones diarias",
    contactManager: "Contacta a tu encargado de obra para obtener tus credenciales",
    signingIn: "Entrando...",

    yourLocation: "Tu Ubicación",
    refreshGps: "Actualizar GPS",
    gettingLocation: "Obteniendo...",
    attendance: "Asistencia",
    onSite: "En obra",
    offSite: "Fuera de obra",
    clockIn: "Fichar Entrada",
    clockOut: "Fichar Salida",
    clockingIn: "Obteniendo GPS y fichando...",
    clockingOut: "Obteniendo GPS y fichando...",
    clockedInAt: "Entrada registrada a las",
    registeredAt: "Registrado en",
    updateMyLocation: "Actualizar Mi Ubicación",
    updatingLocation: "Actualizando...",
    noGpsOnEntry: "No se registró ubicación GPS al entrar",
    viewMap: "Mapa",
    viewOnMap: "Ver en el mapa",
    gpsUnavailable: "El GPS no está disponible en este dispositivo",
    gpsPermissionDenied: "Acceso a ubicación denegado. Activa el GPS en la configuración del navegador.",
    gpsSignalUnavailable: "Señal GPS no disponible. Intenta fuera o en otro lugar.",
    gpsTimeout: "La solicitud de ubicación ha caducado. Inténtalo de nuevo.",
    gpsError: "No se pudo obtener la ubicación. Inténtalo de nuevo.",
    gpsWillBeRecorded: "Se registrará tu ubicación GPS al fichar la entrada",

    teamChat: "Chat del Equipo",
    messages: "mensajes",
    noMessages: "Sin mensajes aún. ¡Inicia la conversación!",
    typeMessage: "Escribe un mensaje...",
    send: "Enviar",

    dailyUpdate: "Publicar Actualización Diaria",
    whatDidYouWork: "¿En qué trabajaste hoy? Describe tu progreso...",
    addPhoto: "Añadir foto",
    changePhoto: "Cambiar foto",
    remove: "Quitar",
    post: "Publicar",
    posting: "Publicando...",
    yourUpdates: "Tus Actualizaciones",
    locationUpdated: "Ubicación actualizada",
    locationUpdatedDesc: "Tu ubicación GPS ha sido actualizada.",
    clockedIn: "Entrada registrada",
    clockedInWithGps: "Has fichado la entrada con tu ubicación GPS.",
    clockedInNoGps: "Has fichado la entrada (GPS no disponible).",
    clockedOut: "Salida registrada",
    clockedOutWithGps: "Has fichado la salida con tu ubicación GPS.",
    clockedOutNoGps: "Has fichado la salida (GPS no disponible).",
    updatePosted: "Actualización publicada",
    updatePostedDesc: "Tu actualización diaria ha sido enviada.",

    leaveRequests: "Solicitudes de Ausencia",
    submitLeaveRequest: "Enviar Solicitud",
    annualLeave: "Vacaciones Anuales",
    sickNote: "Baja por Enfermedad",
    requestType: "Tipo de solicitud",
    startDate: "Fecha inicio",
    endDate: "Fecha fin",
    additionalNotes: "Notas adicionales (opcional)",
    sickNotePhoto: "Foto del justificante médico",
    attachSickNote: "Adjuntar justificante médico",
    changeSickNote: "Cambiar foto",
    submitRequest: "Enviar solicitud",
    submitting: "Enviando...",
    myRequests: "Mis solicitudes",
    pending: "Pendiente",
    approved: "Aprobada",
    rejected: "Rechazada",
    from: "Desde",
    to: "Hasta",
    adminNote: "Nota del administrador",
    requestSubmitted: "Solicitud enviada",
    requestSubmittedDesc: "Tu solicitud de ausencia ha sido enviada.",
    noRequestsYet: "Sin solicitudes enviadas aún.",

    workers: "Trabajadores",
    totalWorkers: "Total trabajadores",
    onSiteNow: "En obra ahora",
    completed: "Han salido",
    activeSites: "Obras activas",
    currentlyOnSite: "Actualmente en obra",
    completedShift: "Turno completado",
    noAttendanceToday: "Sin registros de asistencia para esta fecha.",
    active: "Activo",
    done: "Hecho",
    noGps: "Sin GPS",
    export: "Exportar Excel",
    exportFrom: "Exportar desde",
    payroll: "Nóminas",
    sites: "Obras",
    activity: "Actividad",
    requests: "Solicitudes",
    allRequests: "Todas las solicitudes de ausencia",
    noRequestsAdmin: "Sin solicitudes de ausencia aún.",
    approve: "Aprobar",
    reject: "Rechazar",
    viewSickNote: "Ver justificante",
    pendingRequests: "Pendientes",
    approvedRequests: "Aprobadas",
    rejectedRequests: "Rechazadas",
    approveRequest: "Aprobar solicitud",
    rejectRequest: "Rechazar solicitud",
    optionalNote: "Nota opcional para el trabajador...",
    confirm: "Confirmar",
    cancel: "Cancelar",
    requestApproved: "Solicitud aprobada",
    requestRejected: "Solicitud rechazada",

    addWorker: "Añadir trabajador",
    addNewWorker: "Añadir nuevo trabajador",
    fullName: "Nombre completo",
    fullNamePlaceholder: "ej. Juan García",
    usernamePlaceholder: "ej. juan.garcia",
    passwordPlaceholder: "Establece una contraseña",
    shareWithWorker: "Compartir con el trabajador:",
    copy: "Copiar",
    createWorker: "Crear trabajador",
    creating: "Creando...",
    copied: "Copiado",
    credentialsCopied: "Credenciales copiadas al portapapeles",
    workerCreated: "Trabajador creado",
    workerCreatedDesc: "El nuevo trabajador ha sido añadido correctamente.",
    deleteWorker: "Eliminar trabajador",
    confirmDeleteWorker: "Eliminar",
    workerDeleted: "Trabajador eliminado",
    contract: "Contrato",
    history: "Historial",
    noAttendanceYet: "Sin registros de asistencia aún.",
    workerManagement: "Gestión de trabajadores",
    contractExpired: "Expirado",
    contractExpiringSoon: "Vence pronto",
    contractExpiresIn: "El contrato vence en",
    contractExpiredDaysAgo: "Contrato expirado hace",
    daysLeft: "días restantes en el contrato",
    daysAgo: "días",
    contractType: "Tipo de contrato",
    assignedSite: "Obra asignada",
    hourlyRate: "Tarifa por hora (£)",
    contractStart: "Fecha inicio contrato",
    contractEnd: "Fecha fin contrato",
    totalSickDays: "Total días de baja",
    usedSickDays: "Días de baja usados",
    totalHolidayDays: "Total días de vacaciones",
    usedHolidayDays: "Vacaciones usadas",
    saveContract: "Guardar datos del contrato",
    saving: "Guardando...",
    contractUpdated: "Contrato actualizado",
    sickDaysLeft: "Días de baja restantes",
    holidayDaysLeft: "Días de vacaciones restantes",
    fullTime: "Tiempo completo",
    partTime: "Tiempo parcial",
    temporary: "Temporal",
    byProject: "Por obra",
    apprentice: "Aprendiz",
    noAssignedSite: "Sin obra asignada",

    payrollCalculator: "Calculadora de nóminas",
    noHourlyRate: "Sin tarifa",
    hoursToday: "h hoy",
    setHourlyRate: "Establece la tarifa por hora en cada trabajador para ver los cálculos aquí.",
    enableAlerts: "Activar alertas",
    alertsEnabled: "Alertas activadas",

    addSite: "Añadir obra",
    addSiteTitle: "Añadir obra",
    siteName: "Nombre de la obra",
    siteNamePlaceholder: "ej. Edificio Centro Ciudad",
    siteAddress: "Dirección (opcional)",
    siteAddressPlaceholder: "ej. Calle Mayor 123",
    adding: "Añadiendo...",
    noSitesYet: "Sin obras aún. Añade la primera arriba.",
    noWorkersAssigned: "Sin trabajadores asignados",
    assignedWorkers: "Trabajadores",
    deleteSite: "Eliminar obra",
    siteAdded: "Obra añadida",
    siteDeleted: "Obra eliminada",

    activityTitle: "Actualizaciones de trabajadores",
    noActivityYet: "Sin actualizaciones aún. Los trabajadores pueden publicar desde su portal.",
    unknown: "Desconocido",

    attendanceHistory: "Historial de asistencia",
    viewDate: "Ver fecha",
    today: "Hoy",
  },
};

type Translations = typeof translations.en;

type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("resolve_lang");
    return (saved === "en" || saved === "es") ? saved : "es";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("resolve_lang", l);
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
